### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by nelson-ong-97** [IvanAdmaers/react-roulette-pro#12]
I'm wondering if we can customize the UI as a PieChart(canvas) and is there any available option to do this for now?
My purpose is creating a Wheel like this with the image in each segment

<img width="633" alt="Screen Shot 2022-10-11 at 09 48 09" src="https://user-images.githubusercontent.com/61964358/194985721-424d4441-bd9b-42e7-a1ee-c76dc3e82ffd.png">

**Comment by IvanAdmaers** [comment]
Hello, @StevenOng97. Thank you for your interest in this package.

I had an idea to add one more roulette type that would make the roulette looks like a circle. But at this moment I think it won't be implemented in foreseeable future because of current design of the roulette. It's hard enough and will take lots of time. I'd like to recommend you to see the video - [https://youtu.be/KdFp12QX-Io](https://youtu.be/KdFp12QX-Io) about the round roulette with images. I think it might be helpful.

**Comment by IvanAdmaers** [comment]
If you'll have another question feel free to open a new issue.
