### ISSUE TITLE
Support StaticImageData

### ISSUE THREAD

**Issue by uncle-ara** [IvanAdmaers/react-roulette-pro#19]
Hi. 
I am using Nextjs and the image is of StaticImageData type. 
Unfortunately, in the PrizeType, wants the string type. Could you add support?

I tried to work around this with prizeItemRenderFunction — it worked. But, I noticed there were lags. Probably because my SVG files are being rendered. This is a strange observation.

**Comment by IvanAdmaers** [comment]
Hi, @uncle-ara. Ok, I’ll take a look on it and let you know.

**Comment by uncle-ara** [comment]
@IvanAdmaers, thank you very much

**Comment by IvanAdmaers** [comment]
Would you mind telling me please do you do something like:

```ts
import Image from 'next/image';

const prizes = [
  {
   id: 1,
   image: <Image src=“./test.png”>
  }
]
```

Right?

**Comment by uncle-ara** [comment]
```javascript
export const cardImages: Record<string, JSX.Element> = {
  [cardsType.green]: <IconSVG name="green" />,
  [cardsType.pink]: <IconSVG name="pink" />,
  [cardsType.violet]: <IconSVG name="violet" />,
}

**Comment by uncle-ara** [comment]
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/47677284/213912786-f4063f56-394c-4322-886c-b0149d55e1b1.png">

**Comment by uncle-ara** [comment]
> Would you mind telling me please do you do something like:
> 
> ```ts
> import Image from 'next/image';
> 
> const prizes = [
>   {
>    id: 1,
>    image: <Image src=“./test.png”>
>   }
> ]
> ```
> 
> Right?

While I was trying to explain my problem to you. And I tried to use <Image /> 

And there are no brakes anymore) 
Sorry for your wasted time. Thank you very much.
```<Image/>```  — optimizes image rendering, Nextjs does it, but I wonder what's wrong with SVG :D

```javascript
export const cards = [
  { image: 'green' },
  { image: 'pink' },
  { image: 'violet' },
]

export const cardImages: Record<string, StaticImageData> = {
  [cardsType.green]: green,
  [cardsType.violet]: violet,
  [cardsType.pink]: pink,
}
```
```javascript
prizeItemRenderFunction: ({ id, image }) => {
              return (
                <div key={id} className={styles.item}>
                  <Image
                    src={cardImages[image]}
                    width={103}
                    height={103}
                    alt="icon"
                  />
                </div>
              )
            },

**Comment by uncle-ara** [comment]
The last thing I wanted to ask. My standard position is not centered.
The fact is that I have an interval between columns-gap: 14px.

Maybe I'm setting the wrong value in the width of the prize element: 115px? (map width 101 pixels)

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/47677284/213920016-eb053502-5673-4f0e-833d-94a3a2c5d31b.png">

**Comment by IvanAdmaers** [comment]
Yes, it's due to columns-gap. I can suggest these things:

1) Do not use columns-gap. Use margin instead.
2) Add your gap interval to the prize item. I mean if your single prize element width is 100px and your gap is 14px => 100 + 14 = 114px. Try to set this width to the prize item and padding to keep the prize item needed width.

If this doesn't work you can send me a sample in CodeSandbox and I'll try to match the perfect solution for your case.

**Comment by uncle-ara** [comment]
> Yes, it's due to columns-gap. I can suggest these things:
> 
> 1. Do not use columns-gap. Use margin instead.
> 2. Add your gap interval to the prize item. I mean if your single prize element width is 100px and your gap is 14px => 100 + 14 = 114px. Try to set this width to the prize item and padding to keep the prize item needed width.
> 
> If this doesn't work you can send me a sample in CodeSandbox and I'll try to match the perfect solution for your case.

Thanks, I'll try it now.

**Comment by IvanAdmaers** [comment]
Thank you for your feedback! Feel free to open a new issue if you will have any questions.On 22 Jan 2023, at 11:44 a.m., Mehmet Ozensel ***@***.***> wrote:﻿

Yes, it's due to columns-gap. I can suggest these things:

Do not use columns-gap. Use margin instead.
Add your gap interval to the prize item. I mean if your single prize element width is 100px and your gap is 14px => 100 + 14 = 114px. Try to set this width to the prize item and padding to keep the prize item needed width.

If this doesn't work you can send me a sample in CodeSandbox and I'll try to match the perfect solution for your case.

Thanks, I'll try it now.
If this library will be improved and a new version will be released, please add the StaticImageData type for images. =)

**Comment by uncle-ara** [comment]
The card is 101px in size, I made margin: 0 7px.
In props prizeItemWidth: 115px.
The following result came out:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/47677284/213929761-f0f6a595-3304-4429-9639-aa82176be5be.png">

If I wrap the div component RoulettePro

```css
.foo {
  width: 115%;
}
```

Then everything will work well. But is this a normal solution? Not bad?
This way I have one element from the array will go beyond the left edge of the screen.

**Comment by IvanAdmaers** [comment]
101px + 7px * 2 = 115px that’s good. Did you mean 115px or 115%?On 22 Jan 2023, at 12:08 p.m., Ivan Admaers ***@***.***> wrote:﻿Thank you for your feedback! Feel free to open a new issue if you will have any questions.On 22 Jan 2023, at 11:44 a.m., Mehmet Ozensel ***@***.***> wrote:﻿

Yes, it's due to columns-gap. I can suggest these things:

Do not use columns-gap. Use margin instead.
Add your gap interval to the prize item. I mean if your single prize element width is 100px and your gap is 14px => 100 + 14 = 114px. Try to set this width to the prize item and padding to keep the prize item needed width.

If this doesn't work you can send me a sample in CodeSandbox and I'll try to match the perfect solution for your case.

Thanks, I'll try it now.
If this library will be improved and a new version will be released, please add the StaticImageData type for images. =)
